
MAX_LENGTH: 1024  # 序列最大长度
pad_token_id: 0  # pad_token_id
eos_token_id: 2  # eos_token_id
dataset_src_dir: "/data/corpus/sft/common/"  # sft语料所在路径
file_names: ["alpaca-zh/alpaca_gpt4_data_zh.json"]  # sft待处理的数据集，因为数据集很大，按照实际情况按需使用，比如只使用alpaca-zh
dataset_save_dir: "../sft_data"  # 处理好的文件存储路径
max_samples: null  # None表示不限制，不为None用于测试小样本快速验证
max_samples_per_file: 100000  # 每个文件最多能容纳的样本量，用于切分大文件
name: MiniLLM  # 机器人名字
author: Tongjilibo  # 机器人作者
date: 2024年  # 机器人训练时间
